import { spawn } from 'child_process'
import { randomUUID } from 'crypto'
import { buildPrompt } from './prompt.js'

function runCmd(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { cwd })
    let out = ''
    let err = ''
    proc.stdout.on('data', d => { out += d })
    proc.stderr.on('data', d => { err += d })
    proc.on('close', code => code === 0 ? resolve(out.trim()) : reject(new Error(err.trim() || `exit ${code}`)))
  })
}

async function setupBranch(project) {
  if (!project.githubSource) return null
  const branch = `ralph/issue-${project.githubSource.issueNumber}`
  try {
    await runCmd('git', ['checkout', '-b', branch], project.path)
  } catch {
    await runCmd('git', ['checkout', branch], project.path)
  }
  return branch
}

async function createPr(project, agentId, onEvent) {
  if (!project.githubSource) return
  try {
    const { issueNumber, issueTitle, repoFullName } = project.githubSource
    const title = `resolve #${issueNumber}: ${issueTitle}`

    const status = await runCmd('git', ['status', '--porcelain'], project.path)
    if (!status) {
      onEvent({ type: 'agent:log', agentId, data: { type: 'text', text: '[ralph] no changes to commit' } })
      return
    }

    await runCmd('git', ['add', '-A'], project.path)
    await runCmd('git', ['commit', '-m', title], project.path)
    await runCmd('git', ['push', '-u', 'origin', 'HEAD'], project.path)

    const prUrl = await runCmd('gh', [
      'pr', 'create',
      '--title', title,
      '--body', `Resolves #${issueNumber}\n\nGenerated by [Ralph](https://github.com/${repoFullName}).`,
      '--repo', repoFullName,
    ], project.path)

    onEvent({ type: 'agent:pr', agentId, prUrl })
  } catch (e) {
    onEvent({ type: 'agent:stderr', agentId, message: `[ralph] PR creation failed: ${e.message}` })
  }
}

const runningAgents = new Map()

export function startAgent(project, onEvent) {
  const agentId = randomUUID()
  const maxIterations = 30
  let iteration = 0
  let totalCost = 0
  let stopped = false

  onEvent({ type: 'agent:started', agentId, projectId: project.id, projectName: project.name, githubSource: project.githubSource ?? null })

  setupBranch(project).catch(() => {})

  function runIteration() {
    if (stopped || iteration >= maxIterations) {
      onEvent({ type: 'agent:complete', agentId, reason: stopped ? 'stopped' : 'max_iterations' })
      runningAgents.delete(agentId)
      return
    }

    iteration++
    onEvent({ type: 'agent:iteration', agentId, iteration, maxIterations })

    const prompt = buildPrompt(project.path, project.name)
    const env = { ...process.env, CLAUDECODE: undefined }

    const proc = spawn('claude', ['-p', '--output-format', 'stream-json', '--verbose', prompt], {
      env,
      cwd: project.path,
    })

    runningAgents.set(agentId, {
      stop() {
        stopped = true
        proc.kill()
      },
    })

    let buffer = ''
    let complete = false

    proc.stdout.on('data', chunk => {
      buffer += chunk.toString()
      const lines = buffer.split('\n')
      buffer = lines.pop()

      for (const line of lines) {
        if (!line.trim()) continue
        try {
          const data = JSON.parse(line)
          onEvent({ type: 'agent:log', agentId, data })

          if (data.type === 'result') {
            totalCost += data.total_cost_usd ?? 0
            onEvent({ type: 'agent:cost', agentId, cost: totalCost })
            if (data.result?.includes('<promise>COMPLETE</promise>')) {
              complete = true
            }
          }
        } catch {}
      }
    })

    proc.stderr.on('data', chunk => {
      onEvent({ type: 'agent:stderr', agentId, message: chunk.toString() })
    })

    proc.on('close', () => {
      if (stopped) {
        onEvent({ type: 'agent:complete', agentId, reason: 'stopped' })
        runningAgents.delete(agentId)
        return
      }
      if (complete) {
        createPr(project, agentId, onEvent).finally(() => {
          onEvent({ type: 'agent:complete', agentId, reason: 'complete' })
          runningAgents.delete(agentId)
        })
        return
      }
      runIteration()
    })
  }

  runIteration()
  return agentId
}

export function stopAgent(agentId) {
  runningAgents.get(agentId)?.stop()
}
