import { spawn } from 'child_process'
import { mkdir, writeFile, readFile } from 'fs/promises'
import { randomUUID } from 'crypto'
import { tmpdir } from 'os'
import { join } from 'path'
import { buildPrompt } from './prompt.js'
import { ensureRepo } from './repos.js'
import { copyContextToWorktree, hasMemory, appendMemory } from './memory.js'

const AGENT_SETTINGS = {
  permissions: {
    allow: [
      'Bash(npm create *)',
      'Bash(npm install *)',
      'Bash(npm run build)',
      'Bash(* --version)',
      'Bash(* --help *)',
      'Bash(ls*)',
      'Bash(git add *)',
      'Bash(git commit *)',
      'Read(//tmp/**)',
    ],
    deny: [
      'Read(.env*)',
      'Bash(rm *)',
      'Bash(git rm *)',
    ],
    defaultMode: 'acceptEdits',
  },
  sandbox: {
    enabled: true,
    autoAllowBashIfSandboxed: true,
    allowUnsandboxedCommands: true,
    network: {
      allowedDomains: ['laracasts.com'],
    },
    filesystem: {
      allowWrite: ['~/.fastlane'],
      denyWrite: ['./.github'],
      denyRead: ['~/.aws/credentials'],
    },
    excludedCommands: ['docker'],
  },
}

async function writeAgentSettings(cwd) {
  const dir = join(cwd, '.claude')
  await mkdir(dir, { recursive: true })
  await writeFile(join(dir, 'settings.json'), JSON.stringify(AGENT_SETTINGS, null, 2))
}

function runCmd(cmd, args, cwd) {
  return new Promise((resolve, reject) => {
    const proc = spawn(cmd, args, { cwd })
    let out = ''
    let err = ''
    proc.stdout.on('data', d => { out += d })
    proc.stderr.on('data', d => { err += d })
    proc.on('close', code => code === 0 ? resolve(out.trim()) : reject(new Error(err.trim() || `exit ${code}`)))
  })
}

async function setupWorktree(project, agentId) {
  if (!project.githubSource) return null
  const { issueNumber, repoFullName } = project.githubSource
  const branch = `ralph/issue-${issueNumber}`
  const worktreePath = join(tmpdir(), `ralph-${agentId}`)

  const repoPath = await ensureRepo(repoFullName)

  // Try to add worktree on existing branch first, otherwise create it from HEAD
  try {
    await runCmd('git', ['worktree', 'add', worktreePath, branch], repoPath)
  } catch {
    await runCmd('git', ['worktree', 'add', '-b', branch, worktreePath, 'HEAD'], repoPath)
  }

  return { worktreePath, repoPath }
}

async function createPr(project, agentId, worktreePath, repoPath, onEvent) {
  if (!project.githubSource || !worktreePath) return
  try {
    const { issueNumber, issueTitle, repoFullName } = project.githubSource
    const title = `resolve #${issueNumber}: ${issueTitle}`
    const cwd = worktreePath

    const status = await runCmd('git', ['status', '--porcelain'], cwd)
    if (!status) {
      onEvent({ type: 'agent:log', agentId, data: { type: 'text', text: '[ralph] no changes to commit' } })
    } else {
      await runCmd('git', ['add', '-A'], cwd)
      await runCmd('git', ['commit', '-m', title], cwd)
      await runCmd('git', ['push', '-u', 'origin', 'HEAD'], cwd)
    }

    const prUrl = await runCmd('gh', [
      'pr', 'create',
      '--title', title,
      '--body', `Resolves #${issueNumber}\n\nGenerated by [Ralph](https://github.com/${repoFullName}).`,
      '--repo', repoFullName,
    ], cwd)

    onEvent({ type: 'agent:pr', agentId, prUrl })

    // Synthesise codebase learnings into memory (fire-and-forget)
    const [progressNotes, changedFiles] = await Promise.all([
      readFile(join(project.path, 'progress.md'), 'utf8').catch(() => ''),
      runCmd('git', ['diff', '--name-only', 'HEAD~1', 'HEAD'], cwd).catch(() => ''),
    ])
    if (progressNotes.trim()) {
      appendMemory(repoFullName, { issueNumber, issueTitle, progressNotes, changedFiles }).catch(() => {})
    }
  } catch (e) {
    onEvent({ type: 'agent:stderr', agentId, message: `[ralph] PR creation failed: ${e.message}` })
  } finally {
    runCmd('git', ['worktree', 'remove', '--force', worktreePath], repoPath).catch(() => {})
  }
}

const runningAgents = new Map()

export function isRepoRunning(repoFullName) {
  if (!repoFullName) return false
  for (const a of runningAgents.values()) {
    if (a.repoFullName === repoFullName) return true
  }
  return false
}

export function startAgent(project, onEvent) {
  const agentId = randomUUID()
  const maxIterations = 30
  let iteration = 0
  let totalCost = 0
  let stopped = false

  onEvent({ type: 'agent:started', agentId, projectId: project.id, projectName: project.name, githubSource: project.githubSource ?? null })

  let worktreePath = null
  let repoPath = null
  const worktreeReady = setupWorktree(project, agentId)
    .then(result => {
      if (result) {
        worktreePath = result.worktreePath
        repoPath = result.repoPath
      }
    })
    .catch(() => {})

  function runIteration() {
    if (stopped || iteration >= maxIterations) {
      onEvent({ type: 'agent:complete', agentId, reason: stopped ? 'stopped' : 'max_iterations' })
      runningAgents.delete(agentId)
      return
    }

    iteration++
    onEvent({ type: 'agent:iteration', agentId, iteration, maxIterations })

    const cwd = worktreePath ?? project.path
    const memo = project.githubSource ? await hasMemory(project.githubSource.repoFullName) : false
    const prompt = buildPrompt(project.path, project.name, memo)
    const env = { ...process.env, CLAUDECODE: undefined }

    const proc = spawn('claude', ['-p', '--output-format', 'stream-json', '--verbose', prompt], {
      env,
      cwd,
    })

    runningAgents.set(agentId, {
      repoFullName: project.githubSource?.repoFullName ?? null,
      stop() {
        stopped = true
        proc.kill()
      },
    })

    let buffer = ''
    let complete = false

    proc.stdout.on('data', chunk => {
      buffer += chunk.toString()
      const lines = buffer.split('\n')
      buffer = lines.pop()

      for (const line of lines) {
        if (!line.trim()) continue
        try {
          const data = JSON.parse(line)
          onEvent({ type: 'agent:log', agentId, data })

          if (data.type === 'result') {
            totalCost += data.total_cost_usd ?? 0
            onEvent({ type: 'agent:cost', agentId, cost: totalCost })
            if (data.result?.includes('<promise>COMPLETE</promise>')) {
              complete = true
            }
          }
        } catch {}
      }
    })

    proc.stderr.on('data', chunk => {
      onEvent({ type: 'agent:stderr', agentId, message: chunk.toString() })
    })

    proc.on('close', () => {
      if (stopped) {
        onEvent({ type: 'agent:complete', agentId, reason: 'stopped' })
        runningAgents.delete(agentId)
        return
      }
      if (complete) {
        createPr(project, agentId, worktreePath, repoPath, onEvent).finally(() => {
          onEvent({ type: 'agent:complete', agentId, reason: 'complete' })
          runningAgents.delete(agentId)
        })
        return
      }
      runIteration()
    })
  }

  worktreeReady.then(async () => {
    const cwd = worktreePath ?? project.path
    await writeAgentSettings(cwd).catch(() => {})
    if (project.githubSource && worktreePath) {
      await copyContextToWorktree(project.githubSource.repoFullName, cwd).catch(() => {})
    }
    runIteration()
  })
  return agentId
}

export function stopAgent(agentId) {
  runningAgents.get(agentId)?.stop()
}
